### ISSUE TITLE
self parameter gets expanded as module self in macro

### ISSUE THREAD

**Issue by Marwes** [dtolnay/async-trait#46] opened 2019-10-28 14:59 UTC
Minimal reproduction

```
macro_rules! implement_commands {
    (
        $tyargs:ident : $ty:ident
    ) => {
        #[async_trait]
        pub trait AsyncCommands: Sized {
            async fn f<$tyargs: $ty>(&mut self, x: $tyargs) {
                self.f(x).await
            }
        }
    };
}

implement_commands! { K: Send }
```

```
error[E0424]: expected value, found module `self`
   --> tests/test.rs:434:9
    |
434 |         #[async_trait]
    |         ^^^^^^^^^^^^^^ `self` value is a keyword only available in methods with `self` parameter
...
443 | implement_commands! { K: Send }
    | ------------------------------- in this macro invocation
```

**Comment by dtolnay** [comment] 2019-10-28 15:13
Thanks! Looks like some kind of span issue because the code we are emitting does work by itself. I will take a look in the next couple days (but I would gladly accept a PR to fix this if you get to it first).

Here is the code we currently expand this to:

```rust
pub trait AsyncCommands: Sized {
    fn f<'life0, 'async_trait, K: Send>(
        &'life0 mut self,
        x: K,
    ) -> ::core::pin::Pin<
        Box<dyn ::core::future::Future<Output = ()> + ::core::marker::Send + 'async_trait>,
    >
    where
        K: 'async_trait,
        'life0: 'async_trait,
        Self: ::core::marker::Send + 'async_trait,
    {
        #[allow(clippy::used_underscore_binding)]
        async fn __f<K: Send, AsyncTrait: ?Sized + AsyncCommands + ::core::marker::Send>(
            _self: &mut AsyncTrait,
            x: K,
        ) {
            _self.f(x).await
        }
        Box::pin(__f::<K, Self>(self, x))
    }
}
```

**Comment by dtolnay** [comment] 2019-10-29 18:42
This is being caused by https://github.com/rust-lang/rust/issues/43081 which means unfortunately there is nothing we can do about it in async-trait. The compiler loses all span information on the macro input before it's even passed in to async-trait, which makes `self` in the input meaningless.

```console
TokenStream [
    Ident {
        ident: "pub",
        span: #0 bytes(0..0),
    },
    Ident {
        ident: "trait",
        span: #0 bytes(0..0),
    },
    Ident {
        ident: "AsyncCommands",
        span: #0 bytes(0..0),
    },
    Punct {
        ch: ':',
        spacing: Alone,
        span: #0 bytes(0..0),
    },
    Ident {
        ident: "Sized",
        span: #0 bytes(0..0),
    },
    Group {
```

As a workaround, for some reason the compiler doesn't mess up if you use $:tt in the macro variables instead.

```rust
($tyargs:tt : $ty:tt) => {
```

**Comment by tyranron** [comment] 2020-02-05 09:27
@dtolnay is this a compiler bug which will be fixed eventually, or intended compiler behavior?

**Comment by fundon** [comment] 2020-04-25 17:30
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6a2df01f9171b8fc26d6f2b891eb7757
@dtolnay

**Comment by dtolnay** [comment] 2020-04-25 17:42
This is a compiler bug. I'll lock this for now because we are basically blocked on the compiler handing those macro inputs correctly.

**Closed** 2020-06-08 23:41 UTC
Labels: rustc bug
