### ISSUE TITLE
impl Trait in another crate can't be compiled

### ISSUE THREAD

**Issue by alex-dukhno** [dtolnay/async-trait#109] opened 2020-06-16 17:58 UTC
Hi there,

I've got the following case:
```rust
// crate `interface`
#[async_trait]
pub trait MyInterface {
  async fn function() -> Result<(), Error>;
}

// crate `implementation`
pub struct Implementation;
 
#[async_trait]
impl MyInterface for Implementation {
  async fn function() -> Result<(), Error> {
    Ok(())
  }
}
```

when I compiling the project I got the following compiler error:
```shell-script
error[E0433]: failed to resolve: could not find `pin` in `core`
  --> src/node/src/query_listener.rs:32:1
   |
32 | #[async_trait]
   | ^^^^^^^^^^^^^^ could not find `pin` in `core`

error[E0433]: failed to resolve: could not find `future` in `core`
  --> src/node/src/query_listener.rs:32:1
   |
32 | #[async_trait]
   | ^^^^^^^^^^^^^^ could not find `future` in `core`

error[E0433]: failed to resolve: could not find `marker` in `core`
  --> src/node/src/query_listener.rs:32:1
   |
32 | #[async_trait]
   | ^^^^^^^^^^^^^^ could not find `marker` in `core`
```

Thank you

**Comment by dtolnay** [comment] 2020-06-16 18:02
Can you provide a minimal git repo or something which I could `cargo build` to reproduce this?

**Comment by alex-dukhno** [comment] 2020-06-16 19:00
Hi, thank you for quick response.

Seems like the case is much more complicated then I thought ... 
I created repo https://github.com/alex-dukhno/async-trait-cross-crates-compilation, but I couldn't reproduce the exact error ... but I got the other ...
Trait has `Self::Item` return value in
https://github.com/alex-dukhno/async-trait-cross-crates-compilation/blob/master/src/interface/src/lib.rs#L9
but I had to return reference in impl https://github.com/alex-dukhno/async-trait-cross-crates-compilation/blob/master/src/implementation/src/some_module.rs#L14

I don't know if it suites you but I can give you a link to the branch of my repo where original problem can be reproduced. Here it is https://github.com/alex-dukhno/database/tree/initial-extraction-of-api-for-pg-wire-protocol

**Comment by dtolnay** [comment] 2020-06-16 19:19
It looks like you've provided your own implementation of `core` [here](https://github.com/alex-dukhno/database/blob/3801cf1ae3737319e1824999d43dcb793960e02a/src/core/Cargo.toml#L2) which has an API that is different from libcore (https://doc.rust-lang.org/core/). Similar to `std`, `core` is reserved in Rust to refer to crates which provide the API of libcore, so I am not surprised that it leads to problems. I'll close this issue since a nonstandard libcore is not a setup that we could support.

**Closed by dtolnay** 2020-06-16 19:19 UTC

**Comment by alex-dukhno** [comment] 2020-06-16 19:24
Thanks. Then I’ll rename the create
