### ISSUE TITLE
async_trait uses the raw `Box` identifier rather than a fully qualified path

### ISSUE THREAD

**Issue by Stonks3141** [dtolnay/async-trait#214] opened 2022-09-19 14:19 UTC
This prevents you from writing an async trait called `Box` or using `async_trait` when something else called `Box` is in scope.

Example ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7873638f5bf2adbe016f918c26a65265)):

```rust
#[async_trait]
trait Box {
    async fn foo();
}
```

This expands to

```rust
trait Box {
    #[must_use]
    #[allow(clippy :: type_complexity, clippy :: type_repetition_in_bounds)]
    fn foo<'async_trait>()
    ->
        ::core::pin::Pin<Box<dyn ::core::future::Future<Output = ()> +
        ::core::marker::Send + 'async_trait>>;
}
```

Since the attribute macro uses the Box name as-is from the prelude instead of `std::boxed::Box` or `alloc::boxed::Box`, the compiler doesn't know you don't mean the `Box` trait.

I would think this could be fixed by replacing `Box` with `alloc::boxed::Box` in the macro output. This would mean that `extern crate alloc` would have to be added to the macro output somehow.

**Comment by dtolnay** [comment] 2022-11-26 20:19
Duplicate of #163.

**Closed by dtolnay** 2022-11-26 20:19 UTC
