### ISSUE TITLE
Feature: Adding Sync bound on Future

### ISSUE THREAD

**Issue by Mubelotix** [dtolnay/async-trait#248] opened 2023-06-07 13:57 UTC
I need a trait method to return a Future of this kind:

```rust
Pin<Box<dyn Future<Output = ...> + Send + Sync + 'static>>
```

but all I'm able to obtain with this library is

```rust
Pin<Box<dyn Future<Output = ...> + Send + 'static>>
```

Would it be possible to make the library able to add this `Sync` bound optionally?

We could use this syntax:
 
```rust
#[async_trait(Sync)]
```

If you think this would be relevant, I'm willing to work on implementing this

**Comment by Mubelotix** [comment] 2023-06-07 14:06
Related to #142

**Comment by dtolnay** [comment] 2023-11-12 23:54
This is a duplicate of #77. It's not supported by this crate.

**Closed by dtolnay** 2023-11-12 23:54 UTC
